name: mfl_terminal
description: "Kiosk terminal ui for Model Flight Logbook"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dart_mappable: 4.6.1
  dio: 5.9.1
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  get_it: 9.2.0
  intl: any
  package_info_plus: ^9.0.0
  toastification: 3.0.3
  virtual_keyboard_multi_language: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.10.5
  dart_mappable_builder: ^4.6.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/mfl_logo_slim.png
    - assets/images/bg_image.jpg