name: model_flight_logbook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dart_mappable: ^4.2.2
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  intl: any
  shared_preferences: ^2.2.3
  virtual_keyboard_multi_language: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/mfl_logo_slim.png
    - assets/images/rfid_icon_slim.png